# The Show Object for Stargate from Streaming Availability API,
# which is converted from the JSON of the API response to a Python dict.
show_stargate = \
    {'cast': ['Kurt Russell',
              'James Spader',
              'Jaye Davidson',
              'Viveca Lindfors',
              'Alexis Cruz',
              'Mili Avital',
              'Erick Avari'],
     'directors': ['Roland Emmerich'],
     'genres': [{'id': 'action', 'name': 'Action'},
                {'id': 'adventure', 'name': 'Adventure'},
                {'id': 'scifi', 'name': 'Science Fiction'}],
     'id': '2332',
     'imageSet': {'horizontalPoster': {'w360': 'https://cdn.movieofthenight.com/show/2332/poster/horizontal/en/360.jpg?Expires=1749529668&Signature=Ks8sL~JUXEAP5R42eoiNrSACiELogJG2mfutqilVctyo-HCIaxGNTPDp8ICWSaeDvhTVfk9cNvOq22Pu08iEizzBGbH-SsvSvmsgOXqH~~hq~~iPZGh9NFa5NgEzieBPFOF9AirBYb0ZFW5QCDUZzLnXBH4zf0fBvs8lJJdotAsKpDcHAtWZyZvaf8Y3GL7pCt~k3R1nCANU3WazYFOh-iW19dikJWtm-33j47FjRztuD5bzF~ZOMj607Aet-o5QJLc7Ow~Us-1m3AcUhbv8uurox7sy5XLZC5Z998h2EK8fpB2SzNRlpxjc-t9qFW~ayWpMlcTIQW4vXuUY1co7CQ__&Key-Pair-Id=KK4HN3OO4AT5R',
                                       'w480': 'https://cdn.movieofthenight.com/show/2332/poster/horizontal/en/480.jpg?Expires=1749529668&Signature=ChcwgImEYeVnUw3G1XPjoLS7mx~WzIZy4uhP~kQ4rI2riiD4F1Q9C8yybfk94GbNxf-ABLPDlzFW-mPTtXQIBL0eYB8T4wT8dM9P8EgdtdBwy1ihwjyGIj6IyEIcuMBovFpVBjZyZS2gA~Prt-uO1wQJD2qUNQ5tHdVaO9Nzb3d~NTflFiHVU3uP5a1ZTUIo3gHMJwMAEMuhYX59NYmVcXeE2KJ8Xt8XthaJ2K~~t4q8jeoNa5EUY39-C~VA66nF2QY151RcswwisCPQMt3zmosyaB1FEEPjXu75uolbIglvG0UzEn7o90Z1bdOhUkMKifFIz3Wv0VSrUkdz459ecg__&Key-Pair-Id=KK4HN3OO4AT5R',
                                       'w720': 'https://cdn.movieofthenight.com/show/2332/poster/horizontal/en/720.jpg?Expires=1749529668&Signature=Ir6J2dEqQiAwS8Ar~W10lHkJInYx6D43qYSxUQassSZB73aNWymkoY1eE1-RBXxf5c7-pTyN443wJhbYU7YtbAonMqXjJxszz8wf29~FtFjRt1cM~FD8e5edrnP2laEmqpD8262RhKvPPo-ABXnIHxMSOJwkfbrr2GOgYkHH8SrGu6HiKVG2rbwgd3--8EMPoDD7HLPw8-whbgBQyxKzHBkzpJRMR3pBHMPHHC9PdzL1fZgBLFcG37jH1gej5DFXsZQ1WPszL9LJZhqt5yZgtblfDuhvbYUeQMuwLIm-SrjwgfydFuEcaivNMOSbj2aMCzZtjBD5onh4sd8U3d9QSw__&Key-Pair-Id=KK4HN3OO4AT5R'},
                  'verticalPoster': {'w240': 'https://cdn.movieofthenight.com/show/2332/poster/vertical/en/240.jpg?Expires=1749529667&Signature=NaORR1OjKQUkLgu81X0FspTqG4B93JTPLHVbolWvbBVlcc~-L-Fr1~TWCkK3yLgRAWmeprazD2YBHLz5DyEy73mu088il9Y20ZQBHnkuYMB38HkGnvom-YHacpLLPoamGbQz8CspGnrbI2WX0aaulfFl6GpIhJkCH0UqFqYswQaOeuTSKdPTdbIYd8iT0Gswv4-1Zy5jG-Lm32RVlDHupCS7lQMz8tx2F5n0Kzk649fjpcsTaCMvxKummyBxgr4lQTbwuguCQ~jFiCAih1lEIf53K2olW3b~1IXYDFIGWTZXWVctdl7~1-tvmLIWg7B4~cO7akZgLTFLQzaeGIPb2A__&Key-Pair-Id=KK4HN3OO4AT5R',
                                     'w360': 'https://cdn.movieofthenight.com/show/2332/poster/vertical/en/360.jpg?Expires=1749529667&Signature=WGob9mfNf8Fa0wV8TJLweG3GCkB1bpX0jZ6EV4fqECOjL1ZtjoCX7AA4CczYgd-7uLBJTZa--Ww9ZWMDkrF14iawkAqWiZmYfAL2BmxTpzSXSY1QNX0~4E~ZnUNf5chPNGFkxSSJLzZsGmv9EIGzzPykisLYBaGI5iMdtowr6WJPon~nJlY~BLBMbz9pOWNB-Pk1NZdLGIUnv95jo0uuEnpXghynnjDrsOf6r5lyLJbTApfFXmtqSOZLQjBWw~VzdVt7KVq72JEZvecLFmbYm0hlRNGT1d6toJt4azO37yI1SfW6pF7ChUdl-7AFXIddxbrK5Naz4PaODMTb1FftVQ__&Key-Pair-Id=KK4HN3OO4AT5R',
                                     'w480': 'https://cdn.movieofthenight.com/show/2332/poster/vertical/en/480.jpg?Expires=1749529667&Signature=deGbhmk5vnJ8edis2ShFjvEL0l~QBfriQJJUKEX8We9IW39IJv8QSMYMM7rLunZ-F~3iMdzpyJPslhpfCOatpnfJEFpMqbFsHj822QMX1QTNODRHeJSVDZ55vysgMNctq8g~bOzNuKROjLy95DxNHlnjd1u9kVEhCT0vgwxDThoZNc-Rr5zUj97GViA7H7d8gIhdzHSgfcf39luWE5J426ylyvSoZNbLDgmjUD0-RpPznEDQhjkQk8fLQgoN7-TZz9zt8jATTm146eF7ZsoeAhCN9gQ6MQCnTCuwvgtNycctE4xUzDnxPXZiokI9Yd6OHia-jenkI0I6iHAjdWUbKA__&Key-Pair-Id=KK4HN3OO4AT5R'}},
     'imdbId': 'tt0111282',
     'itemType': 'show',
     'originalTitle': 'Stargate',
     'overview': 'A historical expert and a military unit travel through a '
     'mysterious portal. They land in a bizarre world occupied by a '
     'dangerous and powerful being.',
     'rating': 68,
     'releaseYear': 1994,
     'runtime': 121,
     'showType': 'movie',
     'streamingOptions': {'us': [{'audios': [{'language': 'eng'}],
                                  'availableSince': 1713131980,
                                  'expiresSoon': False,
                                  'link': 'https://www.amazon.com/gp/video/detail/B07MFFB2LP/ref=atv_dp',
                                  'quality': 'sd',
                                  'service': {'homePage': 'https://www.amazon.com/gp/video/storefront/',
                                              'id': 'prime',
                                              'imageSet': {'darkThemeImage': 'https://media.movieofthenight.com/services/prime/logo-dark-theme.svg',
                                                           'lightThemeImage': 'https://media.movieofthenight.com/services/prime/logo-light-theme.svg',
                                                           'whiteImage': 'https://media.movieofthenight.com/services/prime/logo-white.svg'},
                                              'name': 'Prime Video',
                                              'themeColorCode': '#00A8E1'},
                                  'subtitles': [{'closedCaptions': True,
                                                 'locale': {'language': 'eng'}}],
                                  'type': 'subscription'},
                                 {'audios': [],
                                  'availableSince': 1715727453,
                                  'expiresSoon': False,
                                  'link': 'https://pluto.tv/gsa/on-demand/movies/5ca2afdf2ecfdaae49357414/details',
                                  'service': {'homePage': 'https://pluto.tv/',
                                              'id': 'plutotv',
                                              'imageSet': {'darkThemeImage': 'https://media.movieofthenight.com/services/plutotv/logo-dark-theme.svg',
                                                           'lightThemeImage': 'https://media.movieofthenight.com/services/plutotv/logo-light-theme.svg',
                                                           'whiteImage': 'https://media.movieofthenight.com/services/plutotv/logo-white.svg'},
                                              'name': 'Pluto TV',
                                              'themeColorCode': '#fff200'},
                                  'subtitles': [],
                                  'type': 'free',
                                  'videoLink': 'https://pluto.tv/gsa/on-demand/movies/5ca2afdf2ecfdaae49357414'},
                                 {'audios': [],
                                  'availableSince': 1716064222,
                                  'expiresOn': 1727740799,
                                  'expiresSoon': False,
                                  'link': 'https://tubitv.com/movies/475643/stargate',
                                  'quality': 'hd',
                                  'service': {'homePage': 'https://tubitv.com/',
                                              'id': 'tubi',
                                              'imageSet': {'darkThemeImage': 'https://media.movieofthenight.com/services/tubi/logo-dark-theme.svg',
                                                           'lightThemeImage': 'https://media.movieofthenight.com/services/tubi/logo-light-theme.svg',
                                                           'whiteImage': 'https://media.movieofthenight.com/services/tubi/logo-white.svg'},
                                              'name': 'Tubi',
                                              'themeColorCode': '#ffff13'},
                                  'subtitles': [{'closedCaptions': False,
                                                 'locale': {'language': 'eng'}}],
                                  'type': 'free'}]},
     'title': 'Stargate',
     'tmdbId': 'movie/2164'}
